/**
 * Typed demo content. This is the canonical Phase-1 dataset — every page reads
 * through the repositories in src/lib/data, which return this when no database
 * is configured. Replace by seeding the Supabase database (see seed.ts).
 */
import type {
  EventItem,
  GalleryImage,
  GameMode,
  NewsArticle,
  Player,
  Product,
  RuleCategory,
  StaffMember,
  VoteSite,
  TopVoter,
} from "@/lib/types";


export const demoGameModes: GameMode[] = [
  {
    slug: "survival-smp",
    name: "Survival SMP",
    icon: "Pickaxe",
    accent: "green",
    tagline: "A living world that remembers you.",
    description:
      "A rich survival world with custom biomes, land claims, player-run shops, and a genuine economy. Build a base, join a town, and leave a mark that lasts for seasons.",
    players: 86,
    version: "1.21.x",
    features: ["Land claiming & towns", "Player-run shops", "Custom enchantments", "Weekly quest lines", "Seasonal world events"],
    commands: [
      { cmd: "/claim", desc: "Protect a chunk of land as your own." },
      { cmd: "/sethome", desc: "Set a teleport point you can return to." },
      { cmd: "/shop", desc: "Open your player market stall." },
      { cmd: "/quests", desc: "Track your active quest lines." },
    ],
    rules: ["No griefing claimed or community land.", "Scamming in trades is not allowed.", "Lag machines will be removed on sight."],
  },
  {
    slug: "skyblock",
    name: "Skyblock",
    icon: "Sparkles",
    accent: "cyan",
    tagline: "One island. Infinite ambition.",
    description:
      "Start on a single floating island and grow an empire with co-op teams, resource minions, island levels, and seasonal leagues that reset the leaderboard.",
    players: 52,
    version: "1.21.x",
    features: ["Island levels", "Co-op teams", "Resource minions", "Seasonal leagues", "Custom island upgrades"],
    commands: [
      { cmd: "/island", desc: "Create or teleport to your island." },
      { cmd: "/is invite", desc: "Invite a friend to your co-op." },
      { cmd: "/is level", desc: "Check your island's level and rank." },
      { cmd: "/minions", desc: "Manage your resource minions." },
    ],
    rules: ["No cross-island grief via lag.", "Alt-farming island levels is prohibited.", "Co-op trust is your responsibility."],
  },
  {
    slug: "lifesteal",
    name: "Lifesteal",
    icon: "Heart",
    accent: "rose",
    tagline: "Every heart is earned or taken.",
    description:
      "A ruthless open world where killing steals a heart and dying loses one. Forge alliances, set bounties, raid vaults, and survive when the whole server wants you gone.",
    players: 41,
    version: "1.21.x",
    features: ["Heart economy", "Player bounties", "Team vaults", "Combat events", "Withdraw & revive items"],
    commands: [
      { cmd: "/hearts", desc: "Check your current heart count." },
      { cmd: "/bounty", desc: "Place a bounty on a rival." },
      { cmd: "/team", desc: "Create or manage your team." },
      { cmd: "/revive", desc: "Use a revive beacon on a fallen ally." },
    ],
    rules: ["Cross-teaming in solo events is banned.", "No spawn-camping fresh players.", "Client-side combat mods are not allowed."],
  },
  {
    slug: "oneblock",
    name: "OneBlock",
    icon: "Gem",
    accent: "violet",
    tagline: "Break one block. Unlock a world.",
    description:
      "Everything begins with a single, endless block. Mine through twelve progression phases, upgrade your island, meet custom mobs, and prestige for permanent rewards.",
    players: 28,
    version: "1.21.x",
    features: ["12 progression phases", "Island upgrades", "Custom mobs", "Prestige rewards", "Phase leaderboards"],
    commands: [
      { cmd: "/ob", desc: "Teleport to your OneBlock island." },
      { cmd: "/phase", desc: "See your current progression phase." },
      { cmd: "/prestige", desc: "Reset for permanent bonuses." },
      { cmd: "/upgrades", desc: "Open the island upgrade menu." },
    ],
    rules: ["No exploiting phase-skip bugs.", "Report duplication glitches privately.", "Prestige boosting via alts is banned."],
  },
  {
    slug: "kitpvp",
    name: "KitPvP",
    icon: "Swords",
    accent: "orange",
    tagline: "Skill decides everything.",
    description:
      "Fast, balanced combat with ranked duels, custom kits, daily bounties, and ELO matchmaking. No pay-to-win — just you, your aim, and a growing streak.",
    players: 33,
    version: "1.21.x",
    features: ["Ranked duels", "Balanced custom kits", "Daily bounties", "ELO matchmaking", "Kill-streak rewards"],
    commands: [
      { cmd: "/kit", desc: "Select a combat kit." },
      { cmd: "/duel", desc: "Challenge a player to a ranked duel." },
      { cmd: "/elo", desc: "Check your competitive rating." },
      { cmd: "/stats", desc: "View your combat statistics." },
    ],
    rules: ["No teaming in free-for-all zones.", "Combat hacks mean an instant ban.", "No stat-boosting with alt accounts."],
  },
  {
    slug: "creative",
    name: "Creative",
    icon: "Hammer",
    accent: "gold",
    tagline: "Build without limits.",
    description:
      "Claim a generous plot and create with powerful, carefully moderated build tools. Enter build contests, showcase your work at spawn warps, and inspire the network.",
    players: 17,
    version: "1.21.x",
    features: ["Large plots", "WorldEdit access", "Build contests", "Showcase warps", "Collaborative plots"],
    commands: [
      { cmd: "/plot claim", desc: "Claim an empty build plot." },
      { cmd: "/plot trust", desc: "Let a friend build with you." },
      { cmd: "//wand", desc: "Grab the WorldEdit selection tool." },
      { cmd: "/warp showcase", desc: "Visit featured community builds." },
    ],
    rules: ["Keep builds appropriate for all ages.", "No copying builds without credit.", "Respect plot boundaries and trust settings."],
  },
];

const P = (
  username: string,
  rank: string,
  accent: Player["accent"],
  level: number,
  playtimeHours: number,
  kills: number,
  deaths: number,
  wins: number,
  losses: number,
  balance: number,
  blocksMined: number,
  blocksPlaced: number,
  killStreak: number,
  status: Player["status"],
  currentMode: string,
  lastSeen: string,
  firstJoined: string,
  badges: string[],
): Player => ({
  username,
  uuid: `demo-${username.toLowerCase()}-0000-4000-8000-000000000000`,
  rank,
  accent,
  level,
  playtimeHours,
  kills,
  deaths,
  wins,
  losses,
  balance,
  blocksMined,
  blocksPlaced,
  killStreak,
  status,
  currentMode,
  lastSeen,
  firstJoined,
  badges,
  achievements: ["First Blood", "Master Builder", "Season I Veteran", "Event Champion"].slice(0, (level % 4) + 1),
});

export const demoPlayers: Player[] = [
  P("NovaCrafter", "MYTHIC", "gold", 96, 842, 4821, 1210, 214, 88, 2_400_000, 1_284_000, 902_400, 41, "online", "Lifesteal", "now", "2023-10-04", ["Founder's Circle", "Season Champion", "Top 1%"]),
  P("EnderVex", "CHAMPION", "violet", 89, 761, 4410, 1388, 198, 102, 1_800_000, 1_022_300, 764_100, 33, "online", "KitPvP", "now", "2023-10-09", ["Duelist", "Bounty Hunter"]),
  P("LumaForge", "VIP+", "cyan", 82, 694, 3982, 1502, 176, 121, 3_100_000, 1_540_900, 1_204_600, 22, "online", "Skyblock", "now", "2023-11-02", ["Island Baron", "Economist"]),
  P("AetherFox", "VIP", "green", 78, 622, 3711, 1610, 149, 133, 1_200_000, 903_500, 612_000, 18, "offline", "Survival SMP", "2026-07-11T21:40:00Z", "2023-11-18", ["Town Founder"]),
  P("QuartzKing", "MEMBER", "orange", 73, 587, 3450, 1704, 132, 140, 980_000, 812_000, 540_300, 15, "online", "OneBlock", "now", "2024-01-06", ["Prestige III"]),
  P("MossByte", "MEMBER", "rose", 69, 519, 3108, 1611, 121, 118, 760_000, 704_800, 498_200, 12, "offline", "Creative", "2026-07-10T14:05:00Z", "2024-02-14", ["Architect"]),
  P("PixelWraith", "VIP", "violet", 66, 470, 2890, 1440, 110, 96, 640_000, 611_000, 402_100, 9, "online", "Lifesteal", "now", "2024-03-22", ["Raider"]),
  P("CobbleQueen", "MEMBER", "green", 61, 402, 2510, 1288, 98, 90, 540_000, 588_400, 470_000, 8, "online", "Survival SMP", "now", "2024-05-01", ["Merchant"]),
  P("FrostiJim", "MEMBER", "cyan", 58, 366, 2240, 1190, 84, 86, 420_000, 502_200, 351_400, 6, "offline", "Skyblock", "2026-07-09T09:12:00Z", "2024-06-19", []),
  P("EchoStrike", "VIP+", "orange", 55, 341, 2110, 1002, 79, 71, 388_000, 471_000, 300_900, 11, "online", "KitPvP", "now", "2024-07-30", ["Streaker"]),
  P("VerdantAsh", "MEMBER", "green", 49, 288, 1780, 940, 66, 68, 300_000, 410_500, 288_000, 5, "offline", "Survival SMP", "2026-07-08T18:44:00Z", "2024-09-15", []),
  P("SableMint", "MEMBER", "rose", 44, 251, 1502, 812, 58, 60, 264_000, 372_000, 240_100, 4, "online", "OneBlock", "now", "2024-11-03", []),
  P("BasaltBloom", "MEMBER", "gold", 38, 198, 1210, 700, 47, 55, 190_000, 300_400, 198_600, 3, "offline", "Creative", "2026-07-05T12:20:00Z", "2025-01-20", []),
  P("DriftWillow", "MEMBER", "violet", 31, 142, 902, 560, 34, 44, 132_000, 221_000, 150_200, 2, "online", "Skyblock", "now", "2025-04-11", []),
];

export const demoNews: NewsArticle[] = [
  {
    slug: "frontiers-season-two",
    title: "Frontiers Season II has arrived",
    excerpt: "A new survival world, overhauled quests, and the biggest progression update in Mazora history.",
    category: "Server Updates",
    accent: "green",
    date: "2026-07-08",
    author: "The Mazora Team",
    readMinutes: 6,
    body: [
      "Season II of Frontiers is live, and it is the largest content drop we have ever shipped. A brand-new survival world greets you with hand-sculpted biomes, hidden dungeons, and a rebuilt spawn that finally gives the community the hub it deserves.",
      "The quest system has been rewritten from the ground up. Quests now chain into storylines, reward custom items, and adapt to the game mode you are playing. Early questlines ease new players in, while endgame chains will challenge even our most seasoned veterans.",
      "Progression is smoother and more rewarding. Levelling now grants perk points you can spend on your play style, and the new prestige track gives long-term players a reason to keep pushing. We cannot wait to see what you build this season.",
    ],
  },
  {
    slug: "summer-build-festival",
    title: "The Summer Build Festival returns",
    excerpt: "Gather your team and turn an empty island into something the whole network remembers.",
    category: "Events",
    accent: "gold",
    date: "2026-07-04",
    author: "Aria (Events Lead)",
    readMinutes: 4,
    body: [
      "Our biggest community event of the year is back. The Summer Build Festival gives teams two weeks to transform a blank canvas into a showcase build judged by staff and voted on by the community.",
      "This year's theme is \"Worlds Within Worlds\" — we want to see builds that hide entire realms inside them. The top three teams take home exclusive cosmetics, store credit, and a permanent warp at spawn.",
      "Registration opens inside the Creative hub. Grab your friends, claim a festival plot, and start planning. The clock starts the moment the gates open.",
    ],
  },
  {
    slug: "combat-balance-1-8",
    title: "Combat balance update 1.8",
    excerpt: "Refined kits, clearer hit feedback, and a fresh ranked map rotation are now live.",
    category: "Patch Notes",
    accent: "rose",
    date: "2026-06-29",
    author: "Kade (Gameplay)",
    readMinutes: 8,
    body: [
      "Update 1.8 focuses on making combat feel fairer and more readable. We have retuned every KitPvP kit so no single loadout dominates, and adjusted knockback to reward precise movement over spam.",
      "Hit feedback is clearer than ever with new sound cues and particle timing, so you always know when a hit lands. Ranked duels also get three new maps in rotation and a refreshed ELO curve.",
      "Full numbers are in the patch notes channel on Discord. As always, tell us how it feels — balance is a conversation, not a decree.",
    ],
  },
  {
    slug: "anti-cheat-upgrade",
    title: "Next-gen anti-cheat rollout",
    excerpt: "A new detection layer keeps the playing field level without punishing legit players.",
    category: "Development Updates",
    accent: "cyan",
    date: "2026-06-20",
    author: "Dev Team",
    readMinutes: 5,
    body: [
      "Fair play is the foundation Mazora is built on. Our new anti-cheat layer analyses movement and combat patterns server-side, catching cheats faster while dramatically reducing false positives.",
      "Legit players should never notice it. If you are ever wrongly flagged, appeals are reviewed within 24 hours through the support center.",
      "We will keep investing here. A server is only as fun as its worst cheater lets it be — and we intend to keep that number at zero.",
    ],
  },
  {
    slug: "economy-reset-guide",
    title: "Reading the Season II economy",
    excerpt: "How the new player market, taxes, and shop limits keep the economy healthy.",
    category: "Community",
    accent: "green",
    date: "2026-06-12",
    author: "LumaForge (Community)",
    readMinutes: 7,
    body: [
      "A healthy economy makes every trade meaningful. Season II introduces gentle sink mechanics — small market taxes and shop slot limits — that keep inflation in check without punishing active traders.",
      "New players can open a stall from day one, and the /shop interface makes listing items painless. Bulk sellers unlock more slots as their town grows.",
      "This guide walks through pricing basics, avoiding scams, and spotting a good deal. Trade smart out there.",
    ],
  },
  {
    slug: "scheduled-maintenance-july",
    title: "Scheduled maintenance — July 15",
    excerpt: "A short maintenance window to roll out infrastructure upgrades.",
    category: "Maintenance",
    accent: "orange",
    date: "2026-06-30",
    author: "Ops",
    readMinutes: 2,
    body: [
      "We will take the network offline briefly on July 15 from 3:00–4:00 AM IST for infrastructure upgrades that improve tick performance during large events.",
      "No data will be affected. Plan your builds and raids around the window, and watch the Discord status channel for the all-clear.",
      "Thanks for your patience — this one makes the busy nights noticeably smoother.",
    ],
  },
];

export const demoEvents: EventItem[] = [
  {
    slug: "citadel-siege",
    title: "Citadel Siege",
    description: "Two alliances. One fortress. Hold the Citadel through three escalating waves to claim the crown and the prize pool.",
    icon: "Swords",
    accent: "rose",
    startISO: "2026-07-18T14:30:00Z",
    endISO: "2026-07-18T17:00:00Z",
    status: "upcoming",
    mode: "Lifesteal",
    prize: "$250 + Citadel Crown",
    joined: 84,
    maxParticipants: 120,
    requirements: ["Level 20+", "Linked Minecraft account", "Team of 4–6"],
    rewards: ["$250 store credit", "Exclusive Citadel Crown cosmetic", "Winner's warp at spawn"],
    rules: ["No client mods.", "Teams locked at start.", "Staff rulings are final."],
  },
  {
    slug: "skyblock-sprint",
    title: "Skyblock Sprint",
    description: "A timed race to the highest island level. Fresh islands, one week, no mercy for the slow.",
    icon: "Trophy",
    accent: "cyan",
    startISO: "2026-07-24T13:00:00Z",
    endISO: "2026-07-31T13:00:00Z",
    status: "upcoming",
    mode: "Skyblock",
    prize: "50,000 coins",
    joined: 46,
    maxParticipants: 200,
    requirements: ["New sprint island", "Solo or duo"],
    rewards: ["50,000 coins", "Sprint Champion tag", "Vote crate keys"],
    rules: ["Sprint islands only.", "No alt-farming levels.", "Co-op limited to two."],
  },
  {
    slug: "architects-cup",
    title: "Architect's Cup",
    description: "The network's premier build competition. Theme revealed at the opening ceremony.",
    icon: "Crown",
    accent: "gold",
    startISO: "2026-08-02T15:00:00Z",
    endISO: "2026-08-16T15:00:00Z",
    status: "upcoming",
    mode: "Creative",
    prize: "Creator Rank + $150",
    joined: 29,
    maxParticipants: 64,
    requirements: ["Team of 1–4", "Festival plot"],
    rewards: ["Permanent Creator rank", "$150 store credit", "Showcase warp"],
    rules: ["Original builds only.", "No outside schematics.", "Judging is community + staff."],
  },
  {
    slug: "midnight-drop",
    title: "Midnight Drop",
    description: "A surprise loot event happening right now across all survival worlds. Chase the falling crates.",
    icon: "Gift",
    accent: "green",
    startISO: "2026-07-12T00:00:00Z",
    endISO: "2026-07-13T00:00:00Z",
    status: "live",
    mode: "Survival SMP",
    prize: "Rotating loot crates",
    joined: 137,
    maxParticipants: 500,
    requirements: ["Be online", "Survival SMP world"],
    rewards: ["Rare loot crates", "Limited cosmetics", "Bonus coins"],
    rules: ["No crate camping.", "Share the map.", "Have fun."],
  },
  {
    slug: "spring-clash-2026",
    title: "Spring Clash 2026",
    description: "Our completed spring PvP championship — congratulations to every competitor.",
    icon: "Swords",
    accent: "orange",
    startISO: "2026-04-05T14:00:00Z",
    endISO: "2026-04-05T18:00:00Z",
    status: "completed",
    mode: "KitPvP",
    prize: "$300 pool",
    joined: 156,
    maxParticipants: 156,
    requirements: [],
    rewards: ["$300 prize pool split", "Champion cosmetics"],
    rules: ["Archived event."],
    winners: [
      { place: 1, username: "EnderVex", prize: "$150 + Champion tag" },
      { place: 2, username: "EchoStrike", prize: "$100" },
      { place: 3, username: "NovaCrafter", prize: "$50" },
    ],
  },
  {
    slug: "winter-build-2025",
    title: "Winter Build 2025",
    description: "The completed winter build festival that gave us this season's spawn centrepiece.",
    icon: "Hammer",
    accent: "violet",
    startISO: "2025-12-14T15:00:00Z",
    endISO: "2025-12-28T15:00:00Z",
    status: "completed",
    mode: "Creative",
    prize: "Creator Rank",
    joined: 72,
    maxParticipants: 72,
    requirements: [],
    rewards: ["Creator rank", "Build immortalised at spawn"],
    rules: ["Archived event."],
    winners: [
      { place: 1, username: "MossByte", prize: "Creator rank + warp" },
      { place: 2, username: "BasaltBloom", prize: "$100 credit" },
      { place: 3, username: "CobbleQueen", prize: "$50 credit" },
    ],
  },
];

export const demoRules: RuleCategory[] = [
  {
    slug: "general",
    name: "General",
    icon: "Shield",
    updated: "2026-07-01",
    items: [
      { title: "Respect everyone", body: "Treat every player and staff member with respect. Harassment of any kind is not tolerated." },
      { title: "No impersonation", body: "Do not impersonate staff, other players, or Mazora itself." },
      { title: "Keep it appropriate", body: "Usernames, skins, and builds must be suitable for a broad audience." },
      { title: "Follow staff directions", body: "During live incidents, follow staff instructions promptly. You can always appeal afterward." },
    ],
  },
  {
    slug: "chat",
    name: "Chat",
    icon: "MessagesSquare",
    updated: "2026-07-01",
    items: [
      { title: "No hate speech", body: "Slurs, hate speech, and targeted abuse result in an immediate mute or ban." },
      { title: "No spam", body: "Avoid spam, excessive caps, and disruptive formatting in public channels." },
      { title: "No advertising", body: "Advertising other servers or unrelated services is prohibited." },
      { title: "Keep chat readable", body: "Public channels stay in English so moderation remains effective." },
    ],
  },
  {
    slug: "gameplay",
    name: "Gameplay",
    icon: "Gamepad2",
    updated: "2026-06-29",
    items: [
      { title: "No cheats", body: "Hacked clients, macros, and unfair automation are banned across all modes." },
      { title: "No exploits", body: "Do not exploit bugs or duplicate items. Report serious exploits privately to staff." },
      { title: "Play fair", body: "Stat-boosting and alt-farming undermine fair competition and are not allowed." },
    ],
  },
  {
    slug: "pvp",
    name: "PvP",
    icon: "Swords",
    updated: "2026-06-29",
    items: [
      { title: "No spawn camping", body: "Do not repeatedly kill players at spawn or safe zones." },
      { title: "No cross-teaming", body: "Teaming in solo modes and events is prohibited." },
      { title: "Combat mods", body: "Reach, kill-aura, and auto-clickers are an instant ban." },
    ],
  },
  {
    slug: "building",
    name: "Building",
    icon: "Hammer",
    updated: "2026-06-10",
    items: [
      { title: "No griefing", body: "Do not grief protected community areas or other players' claims." },
      { title: "No lag machines", body: "Deliberately harmful redstone or lag machines will be removed." },
      { title: "Respect boundaries", body: "Stay within your plot and claim boundaries." },
    ],
  },
  {
    slug: "economy",
    name: "Economy",
    icon: "Coins",
    updated: "2026-06-12",
    items: [
      { title: "No real-money trades", body: "Selling in-game items for real money outside the store is banned." },
      { title: "No dupe exploits", body: "Item or currency duplication results in a wipe and ban." },
    ],
  },
  {
    slug: "trading",
    name: "Trading",
    icon: "Handshake",
    updated: "2026-06-12",
    items: [
      { title: "No scamming", body: "Scamming is prohibited outside explicitly marked risky modes." },
      { title: "Honor deals", body: "Trades agreed in chat are binding; back out and you may be sanctioned." },
    ],
  },
  {
    slug: "mods-clients",
    name: "Mods & Clients",
    icon: "Cpu",
    updated: "2026-06-29",
    items: [
      { title: "Allowed mods", body: "Performance and cosmetic mods (minimaps without radar, shaders) are allowed." },
      { title: "Banned mods", body: "Any mod that grants a competitive advantage is banned." },
    ],
  },
  {
    slug: "exploits",
    name: "Exploits & Bugs",
    icon: "Bug",
    updated: "2026-06-29",
    items: [
      { title: "Report, don't abuse", body: "Report serious exploits privately through the support center." },
      { title: "No public sharing", body: "Publicly sharing exploits before a fix will be treated as abuse." },
    ],
  },
  {
    slug: "punishments",
    name: "Punishments",
    icon: "Gavel",
    updated: "2026-07-01",
    items: [
      { title: "Escalation", body: "Punishments escalate from warnings to mutes, temp-bans, and permanent bans." },
      { title: "Appeals", body: "Every punishment can be appealed through the support center within 30 days." },
    ],
  },
];

export const demoStaff: StaffMember[] = [
  { username: "Mazora", group: "Owner", title: "Founder & Owner", bio: "Started Mazora in a Discord call in 2023 and never looked back. Sets the vision and signs off on the big swings.", joinDate: "2023-10-01", discord: "mazora", status: "online", accent: "gold" },
  { username: "Aria", group: "Management", title: "Community Manager", bio: "Runs events, herds the team, and makes sure the community always has a voice in the room.", joinDate: "2023-10-05", discord: "aria", status: "online", accent: "green" },
  { username: "Kade", group: "Administrators", title: "Head Administrator", bio: "Keeps the network fair and the moderation team sharp. Balance changes usually have Kade's fingerprints on them.", joinDate: "2023-11-01", discord: "kade", status: "offline", accent: "rose" },
  { username: "Ves", group: "Administrators", title: "Administrator", bio: "Handles appeals and the trickiest support cases with a very level head.", joinDate: "2024-01-12", discord: "ves", status: "online", accent: "violet" },
  { username: "Byte", group: "Developers", title: "Lead Developer", bio: "Writes the plugins that make Mazora feel like Mazora. Lives in the anti-cheat logs.", joinDate: "2023-10-20", discord: "byte", status: "online", accent: "cyan" },
  { username: "Sol", group: "Developers", title: "Developer", bio: "Backend and website. Probably rewrote this exact page.", joinDate: "2024-03-02", discord: "sol", status: "offline", accent: "green" },
  { username: "Wren", group: "Moderators", title: "Senior Moderator", bio: "First on the scene when chat gets spicy. Fair, fast, and unflappable.", joinDate: "2024-02-18", discord: "wren", status: "online", accent: "orange" },
  { username: "Pip", group: "Moderators", title: "Moderator", bio: "Patrols the survival worlds and keeps trades honest.", joinDate: "2024-06-09", discord: "pip", status: "offline", accent: "cyan" },
  { username: "Juno", group: "Helpers", title: "Helper", bio: "Your first friendly face in chat. Loves onboarding new players.", joinDate: "2024-09-14", discord: "juno", status: "online", accent: "green" },
  { username: "Ash", group: "Builders", title: "Lead Builder", bio: "Built the Season II spawn everyone keeps screenshotting.", joinDate: "2023-12-01", discord: "ash", status: "offline", accent: "gold" },
];

export const demoGallery: GalleryImage[] = [
  { id: "g1", title: "Season II Spawn — Aerial", category: "Spawn", accent: "green", author: "Ash" },
  { id: "g2", title: "The Floating Bazaar", category: "Server World", accent: "cyan", author: "LumaForge" },
  { id: "g3", title: "Citadel at Dusk", category: "Events", accent: "rose", author: "EnderVex" },
  { id: "g4", title: "Emberreach Town Hall", category: "Player Builds", accent: "gold", author: "MossByte" },
  { id: "g5", title: "OneBlock Phase 9", category: "Server World", accent: "violet", author: "QuartzKing" },
  { id: "g6", title: "Skyblock Skyline", category: "Player Builds", accent: "cyan", author: "FrostiJim" },
  { id: "g7", title: "Summer Festival Grounds", category: "Events", accent: "gold", author: "Aria" },
  { id: "g8", title: "The Verdant Cathedral", category: "Player Builds", accent: "green", author: "CobbleQueen" },
  { id: "g9", title: "Community Night Fireworks", category: "Community", accent: "orange", author: "Juno" },
  { id: "g10", title: "Nether Hub Redux", category: "Updates", accent: "rose", author: "Byte" },
  { id: "g11", title: "The Archive Library", category: "Player Builds", accent: "violet", author: "BasaltBloom" },
  { id: "g12", title: "Spawn Market District", category: "Spawn", accent: "green", author: "Ash" },
];

export const demoProducts: Product[] = [
  { slug: "rank-hero-monthly", name: "Hero (Monthly)", family: "Hero", billing: "Monthly", category: "Ranks", description: "The first step into Mazora's Survival supporter ranks.", price: 2, features: ["Hero rank benefits", "Monthly access", "Survival SMP"], accent: "green", badge: "Monthly" },
  { slug: "rank-hero-permanent", name: "Hero (Permanent)", family: "Hero", billing: "Permanent", category: "Ranks", description: "Keep the Hero rank and its Survival perks permanently.", price: 6, features: ["Hero rank benefits", "Permanent access", "Survival SMP"], accent: "green", badge: "Permanent" },
  { slug: "rank-veteran-monthly", name: "Veteran (Monthly)", family: "Veteran", billing: "Monthly", category: "Ranks", description: "A stronger monthly Survival rank for regular players.", price: 4, features: ["Veteran rank benefits", "Monthly access", "Survival SMP"], accent: "cyan", badge: "Monthly" },
  { slug: "rank-veteran-permanent", name: "Veteran (Permanent)", family: "Veteran", billing: "Permanent", category: "Ranks", description: "Unlock the Veteran rank permanently on Survival.", price: 8, features: ["Veteran rank benefits", "Permanent access", "Survival SMP"], accent: "cyan", badge: "Permanent" },
  { slug: "rank-vip-monthly", name: "VIP (Monthly)", family: "VIP", billing: "Monthly", category: "Ranks", description: "Premium monthly recognition and perks on Survival.", price: 6, features: ["VIP rank benefits", "Monthly access", "Survival SMP"], accent: "violet", badge: "Monthly" },
  { slug: "rank-vip-permanent", name: "VIP (Permanent)", family: "VIP", billing: "Permanent", category: "Ranks", description: "Permanent VIP status across the Survival experience.", price: 10, features: ["VIP rank benefits", "Permanent access", "Survival SMP"], accent: "violet", badge: "Permanent" },
  { slug: "rank-legend-monthly", name: "Legend (Monthly)", family: "Legend", billing: "Monthly", category: "Ranks", description: "A high-tier monthly rank for dedicated Survival players.", price: 10, features: ["Legend rank benefits", "Monthly access", "Survival SMP"], accent: "orange", badge: "Monthly" },
  { slug: "rank-legend-permanent", name: "Legend (Permanent)", family: "Legend", billing: "Permanent", category: "Ranks", description: "Keep the Legend rank and its perks forever.", price: 25, features: ["Legend rank benefits", "Permanent access", "Survival SMP"], accent: "orange", badge: "Permanent" },
  { slug: "rank-immortal-monthly", name: "Immortal (Monthly)", family: "Immortal", billing: "Monthly", category: "Ranks", description: "Elite monthly status for the Survival community.", price: 12, features: ["Immortal rank benefits", "Monthly access", "Survival SMP"], accent: "rose", badge: "Monthly" },
  { slug: "rank-immortal-permanent", name: "Immortal (Permanent)", family: "Immortal", billing: "Permanent", category: "Ranks", description: "Permanent Immortal status and Survival perks.", price: 29.99, features: ["Immortal rank benefits", "Permanent access", "Survival SMP"], accent: "rose", badge: "Permanent" },
  { slug: "rank-conqueror-monthly", name: "Conqueror (Monthly)", family: "Conqueror", billing: "Monthly", category: "Ranks", description: "Mazora's flagship monthly Survival rank.", price: 14.99, features: ["Conqueror rank benefits", "Monthly access", "Survival SMP"], accent: "gold", badge: "Monthly" },
  { slug: "rank-conqueror-permanent", name: "Conqueror (Permanent)", family: "Conqueror", billing: "Permanent", category: "Ranks", description: "The complete permanent Survival supporter rank.", price: 54.99, features: ["Conqueror rank benefits", "Permanent access", "Survival SMP"], accent: "gold", badge: "Top rank" },

  { slug: "key-vote-5", name: "Vote Keys x5", category: "Crate Keys", description: "Five Vote crate keys for Survival rewards.", price: 0.99, features: ["5 Vote keys", "Survival crate access", "Staff delivery"], accent: "green" },
  { slug: "key-epic-3", name: "Epic Keys x3", category: "Crate Keys", description: "Three Epic crate keys with upgraded rewards.", price: 1.5, features: ["3 Epic keys", "Upgraded loot pool", "Staff delivery"], accent: "cyan" },
  { slug: "key-mystery-3", name: "Mystery Keys x3", category: "Crate Keys", description: "Three Mystery crate keys for surprise rewards.", price: 2.5, features: ["3 Mystery keys", "Mystery reward pool", "Staff delivery"], accent: "violet" },
  { slug: "key-seasonal-2", name: "Seasonal Keys x2", category: "Crate Keys", description: "Two limited Seasonal crate keys.", price: 5, features: ["2 Seasonal keys", "Limited reward pool", "Staff delivery"], accent: "rose", badge: "Seasonal" },
  { slug: "key-spawner-2", name: "Spawner Keys x2", category: "Crate Keys", description: "Two keys for the Survival spawner crate.", price: 7, features: ["2 Spawner keys", "Spawner reward pool", "Staff delivery"], accent: "orange" },
  { slug: "key-legendary-1", name: "Legendary Key x1", category: "Crate Keys", description: "One Legendary key for the premium crate.", price: 7.99, features: ["1 Legendary key", "Premium reward pool", "Staff delivery"], accent: "gold", badge: "Legendary" },

  { slug: "battlepass-premium", name: "Premium Battlepass", category: "Battlepass", description: "Unlock the premium Survival battlepass reward track.", price: 4.5, features: ["Premium reward track", "Survival season access", "Staff activation"], accent: "violet", badge: "Premium" },
  { slug: "battlepass-free-reset", name: "Free Battlepass Reset", category: "Battlepass", description: "Reset your free battlepass progress and start the track again.", price: 3.99, features: ["Free track reset", "Survival battlepass", "Staff activation"], accent: "cyan" },

  { slug: "addon-xp-50", name: "50 XP", category: "Add-ons", subcategory: "XP Boosts", description: "Add 50 XP to your Survival progression.", price: 2.99, features: ["50 Survival XP", "Applied by staff", "Manual delivery"], accent: "green" },
  { slug: "addon-xp-200", name: "200 XP", category: "Add-ons", subcategory: "XP Boosts", description: "Add 200 XP to your Survival progression.", price: 11.5, features: ["200 Survival XP", "Applied by staff", "Manual delivery"], accent: "cyan" },
  { slug: "addon-xp-500", name: "500 XP", category: "Add-ons", subcategory: "XP Boosts", description: "Add 500 XP to your Survival progression.", price: 25.99, features: ["500 Survival XP", "Applied by staff", "Manual delivery"], accent: "gold", badge: "Largest boost" },
  { slug: "addon-claim-1000", name: "1,000 Claim Blocks", category: "Add-ons", subcategory: "Claim Blocks", description: "Expand your protected Survival land by 1,000 blocks.", price: 3, features: ["1,000 claim blocks", "Survival SMP", "Staff delivery"], accent: "green" },
  { slug: "addon-claim-4000", name: "4,000 Claim Blocks", category: "Add-ons", subcategory: "Claim Blocks", description: "Expand your protected Survival land by 4,000 blocks.", price: 11.5, features: ["4,000 claim blocks", "Survival SMP", "Staff delivery"], accent: "cyan" },
  { slug: "addon-claim-8000", name: "8,000 Claim Blocks", category: "Add-ons", subcategory: "Claim Blocks", description: "Expand your protected Survival land by 8,000 blocks.", price: 20.99, features: ["8,000 claim blocks", "Survival SMP", "Staff delivery"], accent: "violet" },
  { slug: "addon-claim-10000", name: "10,000 Claim Blocks", category: "Add-ons", subcategory: "Claim Blocks", description: "Expand your protected Survival land by 10,000 blocks.", price: 28.99, features: ["10,000 claim blocks", "Survival SMP", "Staff delivery"], accent: "orange" },
  { slug: "addon-claim-12000", name: "12,000 Claim Blocks", category: "Add-ons", subcategory: "Claim Blocks", description: "The largest Claim Block package in the Survival store.", price: 34.99, features: ["12,000 claim blocks", "Survival SMP", "Staff delivery"], accent: "gold", badge: "Largest pack" },
  { slug: "addon-pp-50", name: "50 Player Points", category: "Add-ons", subcategory: "Player Points", description: "Add 50 Player Points to your Survival account.", price: 3.25, features: ["50 Player Points", "Survival account", "Staff delivery"], accent: "violet" },
  { slug: "addon-pp-100", name: "100 Player Points", category: "Add-ons", subcategory: "Player Points", description: "Add 100 Player Points to your Survival account.", price: 6.5, features: ["100 Player Points", "Survival account", "Staff delivery"], accent: "gold", badge: "Best value" },
];

export const demoVoteSites: VoteSite[] = [
  { id: "v1", name: "MinecraftServers.org", url: "https://minecraftservers.org/server/688211", reward: "1 Vote Key + 250 coins", cooldownHours: 24 },
  { id: "v2", name: "Minecraft-MP.com", url: "https://minecraft-mp.com/server-s358100", reward: "1 Vote Key + 250 coins", cooldownHours: 24 },
];

export const demoTopVoters: TopVoter[] = [];

